version: '3.5'

services:
  mysql:
    image: mysql:8.0.0
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_WRITE_PASSWORD}"
      MYSQL_DATABASE: "${DB_WRITE_DATABASE}"
      MYSQL_USER: "${DB_WRITE_USERNAME}"
      MYSQL_PASSWORD: "${DB_WRITE_PASSWORD}"
    volumes:
      - database:/var/lib/mysql
      - ./Migration/Initialization/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - 3306:3306
    networks:
      - NetworkFairness
  nginx:
    image: "nginx:1.21.6"
    restart: always
    links:
      - app
      - elasticsearch
    working_dir: /application
    volumes:
      - '.:/application'
      - "./Build/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - NetworkFairness

  app:
    build: ./Build
    working_dir: /application
    volumes:
      - '.:/application'
    links:
      - mysql
      - elasticsearch
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cloud.fairness.tech"
    networks:
      - NetworkFairness
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.monitoring.enabled: "true"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - NetworkFairness

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - NetworkFairness
volumes:
  database:
  esdata:
    driver: local

networks:
  NetworkFairness:
    driver: bridge
    name: NetworkFairness