version: '3.5'

services:
  mysql:
    image: mysql:8
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_WRITE_PASSWORD}"
      MYSQL_DATABASE: "${DB_WRITE_DATABASE}"
      MYSQL_USER: "${DB_WRITE_USERNAME}"
      MYSQL_PASSWORD: "${DB_WRITE_PASSWORD}"
    volumes:
      - database:/application/database
    ports:
      - 3306:3306
    networks:
      - NetworkFairness
  nginx:
    image: "nginx:1.21.6"
    restart: always
    links:
      - app
    working_dir: /application
    volumes:
      - ".:/application"
      - "./Build/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf"
      - "./Build/SSL/fullchain.pem:/etc/nginx/ssl/fullchain.pem"
      - "./Build/SSL/privkey.pem:/etc/nginx/ssl/privkey.pem"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - NetworkFairness

  app:
    build: ./Build
    working_dir: /application
    volumes:
      - '.:/application'
      - './Build/php/local.ini:/usr/local/php/conf.d/local.ini'
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=cloud.fairness.tech"
    networks:
      - NetworkFairness
volumes:
  database:
  esdata:
    driver: local
networks:
  NetworkFairness:
    driver: bridge
    name: NetworkFairness